#include <stdio.h>
#include <string.h>
#include "include/file.h"
#include "include/heap.h"

void print_free_page_list(HeapFile *hf) {
    printf("  Free Page List: ");
    if (hf->header.first_free_page == -1) {
        printf("(empty)\n");
        return;
    }
    HeapPage page;
    int32_t page_id = hf->header.first_free_page;
    while (page_id != -1) {
        printf("[Page %d]", page_id);
        if (read_page(hf, &page, page_id) != GRAIN_OK) break;
        page_id = page.header.next_free_page;
        if (page_id != -1) printf(" -> ");
    }
    printf(" -> NULL\n");
}

void print_free_slot_list(HeapPage *page) {
    printf("  Free Slot List (Page %d): ", page->header.page_id);
    if (page->header.first_free_slot == FREE_SLOT_END) {
        printf("(empty)\n");
        return;
    }
    int32_t slot_idx = page->header.first_free_slot;
    while (slot_idx != FREE_SLOT_END) {
        printf("[Slot %d]", slot_idx);
        FreeSlot *slot = (FreeSlot *)(page->storage + (slot_idx * RECORD_SIZE));
        slot_idx = slot->next_free_slot;
        if (slot_idx != FREE_SLOT_END) printf(" -> ");
    }
    printf(" -> NULL\n");
}

void print_state(HeapFile *hf) {
    printf("\n--- State ---\n");
    printf("  Pages: %d\n", hf->header.num_pages);
    print_free_page_list(hf);
    for (int32_t i = 0; i < hf->header.num_pages; i++) {
        HeapPage page;
        if (read_page(hf, &page, i) == GRAIN_OK) {
            print_free_slot_list(&page);
        }
    }
}

void print_records(HeapFile *hf) {
    RecordId rid = {0, -1};
    Record rec;
    printf("\n--- Records ---\n");
    while (hf_scan_next(hf, &rid, &rec) == GRAIN_OK) {
        printf("  [page=%d, slot=%d] id=%d, name=%s, age=%d\n",
               rid.page_id, rid.slot_idx, rec.id, rec.name, rec.age);
    }
}

int main() {

	/*
		* examples and test cases generated by Claude. i was too lazy for this :|
	*/
    HeapFile *hf = create_file("example.bin");
    if (hf == NULL) {
        printf("Failed to create file\n");
        return 1;
    }
    printf("Created: example.bin\n");

    Record records[] = {
        {.id = 1, .age = 25, .name = "Alice", .email = "alice@example.com"},
        {.id = 2, .age = 30, .name = "Bob", .email = "bob@example.com"},
        {.id = 3, .age = 35, .name = "Charlie", .email = "charlie@example.com"},
        {.id = 4, .age = 28, .name = "Diana", .email = "diana@example.com"},
        {.id = 5, .age = 32, .name = "Eve", .email = "eve@example.com"}
    };

    printf("\n=== Inserting 5 records ===\n");
    for (int i = 0; i < 5; i++) {
        hf_insert_record(hf, &records[i]);
    }
    print_records(hf);
    print_state(hf);

    printf("\n=== Deleting Bob (slot 1) and Diana (slot 3) ===\n");
    hf_delete_record(hf, (RecordId){0, 1});
    hf_delete_record(hf, (RecordId){0, 3});
    print_records(hf);
    print_state(hf);

    printf("\n=== Inserting Frank (reuses free slot) ===\n");
    Record frank = {.id = 6, .age = 40, .name = "Frank", .email = "frank@example.com"};
    hf_insert_record(hf, &frank);
    print_records(hf);
    print_state(hf);

    close_file(hf);
    printf("\nDone.\n");

    return 0;
}
